import type { NextPage } from "next";
import Head from "next/head";
import { useActiveWeb3React } from "hooks/useActiveWeb3React";
import { useEffect } from "react";
import { UnsupportedChainIdError, useWeb3React } from "@web3-react/core";
import { injected } from "config/constants/wallets";
import { connectorLocalStorageKey } from "config/connectors/index";
import { useContract } from "hooks/useContract";
import testAbi from '../abi/test.json'
import { useTranslation } from "react-i18next";

const Home: NextPage = () => {
    const { t, i18n } = useTranslation();
    const { account, chainId, error, activate } = useActiveWeb3React();
    const contract = useContract('0xB60F13A9D370f14aA267E3eCD6af1Ef26F5A004B', testAbi, true)
    useEffect(() => {
        console.log(window.localStorage.getItem(connectorLocalStorageKey));

        activate(injected, undefined, true).catch((error) => {
            activate(injected);
        });
    }, []);
    const testButton = () => {
        console.log(contract?.burn(100));

    }
    return (
        <div>
            <Head>
                <title>BEP1.39</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                {account}---
                {chainId}
                <button onClick={testButton}> {t("title")}</button>
                <button onClick={() => {
                    i18n.changeLanguage("en")
                }}>en</button>
                <button onClick={() => {
                    i18n.changeLanguage("zh")
                }}>zh</button>
            </div>
        </div>
    );
};

export default Home;
